version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medusa"]
      interval: 10s
      timeout: 5s
      retries: 5

  medusa:
    build:
      context: ./apps/medusa
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://medusa:medusa@postgres:5432/medusa
    ports:
      - "9000:9000"
    volumes:
      - ./apps/medusa:/app
    command: ["yarn", "start:prod"]

  storefront:
    build:
      context: ./apps/storefront
      dockerfile: Dockerfile
    depends_on:
      - medusa
    ports:
      - "3000:3000"
    volumes:
      - ./apps/storefront:/app
    command: ["yarn", "start"]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: 