version: '3'
name: medusa2-starter
services:
  db:
    image: postgres:16
    container_name: medusa2-starter-postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'medusa'
      POSTGRES_PASSWORD: 'medusa'
      POSTGRES_DB: 'medusa'
  redis:
    image: redis
    container_name: medusa2-starter-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  database:
  redis:
